### ISSUE TITLE
Naming issues after package renaming

### ISSUE THREAD

**Issue by BrutalPoseidon** [GKS-2018-CollaborativeSoftware/workshop-collaborative_software#2]
After gksolite renaming, the previous name is seen in 
![image](https://user-images.githubusercontent.com/24897533/44790400-8b4c8e00-ab9f-11e8-8d3c-ce0d309d73d8.png)

**Comment by amaltaro** [comment]
Hey @BrutalPoseidon , thanks for reporting this issue, unfortunately this is low priority on our list of issues, so you'll have to wait until it gets fixed by itself.

**Comment by amaltaro** [comment]
Issue hasn't been fixed, so I'm reopening it.

**Comment by BrutalPoseidon** [comment]
I fixed it yesterday
